### ISSUE TITLE
Update for MC 1.16.5 for forge 36.1.13

### ISSUE THREAD

**Issue by keithbandit98** [mchorse/imaginary#1]
hi, i am trying to adapt the code to make it work on minecraft 1.16.5 with forge 36.1.13 but without much success, i hope some developer who worked on it can update this beautiful mod.

**Comment by mchorse** [comment]
Sorry, the mod is abandoned and I’m not modding anymore (technically I’m finishing last updates, so I’m in the progress of quitting).
